BAH-2937 | Add. Job to trigger docker deployments

diff --git a/.github/workflows/proxy_image_build_publish.yml b/.github/workflows/proxy_image_build_publish.yml
--- a/.github/workflows/proxy_image_build_publish.yml
+++ b/.github/workflows/proxy_image_build_publish.yml
@@ -36,3 +36,23 @@ jobs:
           no-cache: true
           push: true
           tags: bahmni/proxy:${{env.ARTIFACT_VERSION}},bahmni/proxy:latest
+  trigger:
+      name: Trigger auto deploy 
+      runs-on: ubuntu-latest
+      needs: docker-build-publish
+      if: ${{ github.event.workflow_run.conclusion == 'success' }}
+      env:
+        ORG_NAME: Bahmni
+        REPOSITORY_NAME: bahmni-docker
+        EVENT_TYPE: bahmni-proxy-publish-event
+      steps:
+        - name: Create repository_dispatch
+          run: |
+            trigger_result=$(curl -s -o trigger_response.txt -w "%{http_code}" -X POST -H "Accept: application/vnd.github.v3+json" -H 'authorization: Bearer ${{ secrets.BAHMNI_PAT }}' https://api.github.com/repos/${ORG_NAME}/${REPOSITORY_NAME}/dispatches -d '{"event_type":"'"${EVENT_TYPE}"'"}')
+            if [ $trigger_result == 204 ];then
+              echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Success"
+            else
+              echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Failed"
+              cat trigger_response.txt
+              exit 1
+            fi
